server:
  port: 8080

spring:
  application:
    name: @pom.artifactId@
  boot:
    admin:
      client:
        url: http://localhost:8085
  jackson:
    serialization:
      indent-output: true
  jmx:
    enabled: true
    default-domain: com.github.aha.sat.rest
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
      generate_statistics: true


springdoc:
  packagesToScan: com.github.aha.sat.rest
  pathsToMatch: /v1, /city/**
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always

sat-rest:
  cfg:
    author: Arny
